### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="session_key-login"]

### ISSUE THREAD

**Issue by Ajinkz** [itsnbyim/LInBot#13]
Launching Firefox/Iceweasel
Traceback (most recent call last):
  File "LInBot.py", line 205, in <module>
    Launch()
  File "LInBot.py", line 38, in Launch
    StartBrowser(browserChoice)
  File "LInBot.py", line 80, in StartBrowser
    emailElement = browser.find_element_by_id('session_key-login')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="session_key-login"]

**Comment by rodrigolopezguerra** [comment]
browser.get('https://linkedin.com/uas/login')
	emailElement = browser.find_element_by_id('username')
	passElement = browser.find_element_by_id('password')
